CREATE TABLE houses (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        address varchar(100) UNIQUE,
                        owner_Id BIGINT
);

CREATE TABLE roles (
                       ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       role varchar(50)
);




CREATE TABLE users (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name varchar(100),
                        age int,
                        login varchar(100) ,
                        password varchar(100),
                        houses_id BIGINT REFERENCES houses(id)
);

CREATE TABLE user_role (
                             role_id BIGINT REFERENCES roles (ID),
                             user_id BIGINT REFERENCES users (ID)
);






